### ISSUE TITLE
Update dependencies with identified vulernabilities

### ISSUE THREAD

**Issue by joshua-rutherford** [DecipherNow/gm-landing-page#22]
The following dependencies have been identified as having vulnerabilities and should be upgraded to the shown version:

`"merge": ">=1.2.1"`
`"randomatic": ">=3.0.0"`

These changes should be made to the `package.json`.

**Comment by Shah-Parth** [comment]
@joshua-rutherford: from what it looks like the dependencies come from `gm-react-script`. If we upgrade jest to the latest version `23.6.0` we may be able to upgrade the nested dependencies. Can you tell me where I can go to upgrade that?

`abc-MBP:gm-landing-page abc$ npm list randomatic
gm-landing-page@0.2.1 /Users/abc/gm-landing-page
└─┬ gm-react-scripts@0.1.0
  └─┬ jest@20.0.4
    └─┬ jest-cli@20.0.4
      └─┬ micromatch@2.3.11
        └─┬ braces@1.8.5
          └─┬ expand-range@1.8.2
            └─┬ fill-range@2.2.4
              └── randomatic@3.1.1 `

`abc-MBP:gm-landing-page abc$ npm list merge
gm-landing-page@0.2.1 /Users/abc/gm-landing-page
└─┬ gm-react-scripts@0.1.0
  └─┬ jest@20.0.4
    └─┬ jest-cli@20.0.4
      └─┬ jest-haste-map@20.0.5
        └─┬ sane@1.6.0
          └─┬ exec-sh@0.2.1
            └── merge@1.2.0 `

**Comment by justincely** [comment]
Closed with #23
